package io.github.fbbzl.starter.mybatisplus.frame;

import com.baomidou.mybatisplus.core.toolkit.PluginUtils;
import com.baomidou.mybatisplus.core.toolkit.StringUtils;
import com.baomidou.mybatisplus.extension.parser.JsqlParserSupport;
import com.baomidou.mybatisplus.extension.plugins.inner.InnerInterceptor;
import io.github.fbbzl.starter.mybatisplus.BaseMybatisPlusEntity;
import net.sf.jsqlparser.expression.JdbcParameter;
import net.sf.jsqlparser.schema.Column;
import net.sf.jsqlparser.statement.update.Update;
import net.sf.jsqlparser.statement.update.UpdateSet;
import org.apache.ibatis.executor.statement.StatementHandler;
import org.apache.ibatis.mapping.BoundSql;
import org.apache.ibatis.mapping.MappedStatement;
import org.apache.ibatis.mapping.ParameterMapping;
import org.apache.ibatis.mapping.SqlCommandType;
import org.apache.ibatis.session.Configuration;

import java.sql.Connection;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicReference;

/**
 * Add delete_at = ?to the UPDATE statement generated by the MyBatis-Plus logical deletion, and fill it with the current LocalDateTime applied.
 *
 * @author fengbinbin
 * @version 1.0
 * @since 2026/6/29
 */
public class LogicDeleteWithDeleteAtInnerInterceptor extends JsqlParserSupport implements InnerInterceptor
{

    private static final String DELETED_COLUMN  = StringUtils.camelToUnderline(BaseMybatisPlusEntity.Fields.deleted);
    private static final String DELETE_AT_COLUMN = StringUtils.camelToUnderline(BaseMybatisPlusEntity.Fields.deleteAt);
    private static final String DELETE_AT_PARAM  = "_logicDeleteDeleteAt";

    @Override
    public void beforePrepare(StatementHandler sh, Connection connection, Integer transactionTimeout)
    {
        PluginUtils.MPStatementHandler mpStatementHandler = PluginUtils.mpStatementHandler(sh);
        MappedStatement                mappedStatement    = mpStatementHandler.mappedStatement();
        if (mappedStatement.getSqlCommandType() != SqlCommandType.UPDATE) {
            return;
        }

        BoundSql               boundSql    = sh.getBoundSql();
        PluginUtils.MPBoundSql mpBoundSql  = PluginUtils.mpBoundSql(boundSql);
        String                 originalSql = mpBoundSql.sql();

        AtomicReference<LocalDateTime> deleteAtRef = new AtomicReference<>();
        String                         parsedSql    = parserMulti(originalSql, deleteAtRef);

        LocalDateTime deleteAt = deleteAtRef.get();
        if (deleteAt != null) {
            mpBoundSql.sql(parsedSql);
            addDeleteAtParameter(mappedStatement.getConfiguration(), mpBoundSql, boundSql, deleteAt);
        }
    }

    @Override
    protected void processUpdate(Update update, int index, String sql, Object obj)
    {
        @SuppressWarnings("unchecked")
        AtomicReference<LocalDateTime> deleteAtRef = (AtomicReference<LocalDateTime>) obj;

        List<Column> setColumns = update.getUpdateSets().stream()
                                        .flatMap(us -> us.getColumns().stream())
                                        .toList();
        if (setColumns.isEmpty()) {
            return;
        }

        boolean isLogicDelete = setColumns.stream()
                                          .anyMatch(col -> DELETED_COLUMN.equalsIgnoreCase(col.getColumnName()));
        if (!isLogicDelete) {
            return;
        }

        boolean alreadyHasDeleteAt = setColumns.stream()
                                               .anyMatch(col -> DELETE_AT_COLUMN.equalsIgnoreCase(col.getColumnName()));
        if (alreadyHasDeleteAt) {
            return;
        }

        update.getUpdateSets().add(0, new UpdateSet(new Column(DELETE_AT_COLUMN), new JdbcParameter()));
        deleteAtRef.set(LocalDateTime.now());
    }

    private void addDeleteAtParameter(Configuration configuration, PluginUtils.MPBoundSql mpBoundSql, BoundSql boundSql, LocalDateTime value)
    {
        ParameterMapping mapping = new ParameterMapping.Builder(configuration, DELETE_AT_PARAM, LocalDateTime.class).build();

        List<ParameterMapping> parameterMappings = new ArrayList<>(mpBoundSql.parameterMappings());
        parameterMappings.add(0, mapping);
        mpBoundSql.parameterMappings(parameterMappings);

        PluginUtils.setAdditionalParameter(boundSql, Map.of(DELETE_AT_PARAM, value));
    }
}
